core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from analytics import views
from django.conf import settings
from django.conf.urls.static import static

from analytics.views import SearchResultsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),

    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('developers/', views.developers, name='developers'),
    path('houses/', views.houses, name='houses'),
    url(r'^search/$', views.search, name='search'),
    path('search_results/', SearchResultsView.as_view(), name='search_results'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analytics/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.core.validators import RegexValidator

HOUSE_CLASSES = (
    ("1", "эконом"),
    ("2", "комфорт"),
    ("3", "премиум"),
)

HOUSE_STATUSES = (
    ("1", "сдан"),
    ("2", "строится"),
)

AVAILABILITY = (
    ("1", "есть"),
    ("2", "проданы"),
)

YEAR = []
for y in range(1990, (datetime.datetime.now().year + 10)):
    YEAR.append((y, y))

FOUNDATION_YEAR = []
for y in range(1990, datetime.datetime.now().year):
    FOUNDATION_YEAR.append((y, y))

PHONE_REGEX = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")


class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)


class Developer(models.Model):
    name = models.CharField('Название строительной компании', max_length=100, blank=False)
    site = models.CharField('Сайт', max_length=100)
    foundation_year = models.IntegerField('Год основания', choices=FOUNDATION_YEAR, default=datetime.datetime.now().year)
    phone_number = models.CharField('Номер телефона', validators=[PHONE_REGEX], max_length=17)
    image = models.FileField('Лого', upload_to='logo/')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Застройщик"
        verbose_name_plural = "Застройщики"


class House(models.Model):
    name = models.CharField('Имя', max_length=100, blank=False)
    year = models.IntegerField('Год ввода в эксплуатацию', choices=YEAR, default=datetime.datetime.now().year)
    number_of_floors = models.PositiveIntegerField('Этажность')
    number_of_apartments = models.PositiveIntegerField('Кол-во квартир')
    house_class = models.CharField('Класс дома', max_length=100, choices=HOUSE_CLASSES)
    status = models.CharField('Статус дома', max_length=100, choices=HOUSE_STATUSES)
    availability_of_apartments = models.CharField('Наличие квартир', max_length=100, choices=AVAILABILITY)
    address = models.CharField('Адрес', max_length=100)
    image = models.FileField('Фото', upload_to='img/')

    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Дом"
        verbose_name_plural = "Дома"

analytics/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, help_text='Required. 100 charaters of fewer.')
    last_name = forms.CharField(max_length=100, help_text='Required. 100 charaters of fewer.')

    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name')

analytics/views.py
from itertools import chain

from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm
from .models import Developer, House
from django.shortcuts import render
from .filters import HouseFilter
from django.views.generic import TemplateView, ListView


def index(request):
    return render(request, 'index.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


def developers(request):
    developer_list = Developer.objects.all()
    return render(request, 'developers.html', {'developers': developer_list})


def houses(request):
    house_list = House.objects.all()
    return render(request, 'houses.html', {'houses': house_list})


def search(request):
    house_list = House.objects.all()
    house_filter = HouseFilter(request.GET, queryset=house_list)

    return render(request, 'search.html', {'filter': house_filter})


class SearchResultsView(ListView):
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_house = House.objects.filter(
            Q(name__icontains=query) | Q(status__icontains=query)
        )
        object_developer = Developer.objects.filter(
            Q(name__icontains=query)
        )
        object_list = list(chain(object_house, object_developer))
        return object_list

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Analytics</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
</head>
<body>

<div class="container-nav" style="justify-content: space-between;">
    <nav id="main-nav" class="navbar navbar-expand-lg navbar-dark bg-dark" style="display: flex;">
        <ul class="navbar-nav">
            <li class="nav-item nav-item-custom">
                <a class="nav-link" href="/">Главная</a>
            </li>
            <li class="nav-item nav-item-custom">
                <a class="nav-link" href="/developers">Застройщики</a>
            </li>
            <li class="nav-item nav-item-custom">
                <a class="nav-link" href="/search">Дома</a>
            </li>
            <li>
                <form action="{% url 'search_results' %}" class="form-inline" style="display: flex;">
                    <input name="q" class="form-control mr-sm-2 nav-item-custom" style="margin-right: 15px;" type="search" placeholder="Поиск" aria-label="Search" />
                    <button class="btn btn-outline-success my-2 my-sm-0 nav-item-custom" type="submit">Поиск</button>
                </form>
            </li>
        </ul>
        <ul class="navbar-nav" style="margin-left: auto">
            <li class="nav-item nav-item-custom form-inline" style="display: flex; justify-content: inline">
                {% if user.is_authenticated %}
                <a class="nav-link">Привет, {{ user.username }}!</a>
                <a class="nav-link" style="padding-left: 10px; padding-right: 10px">|</a>
                <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                {% else %}
                <a class="nav-link" style="align-items: flex-end" href="/login/">Авторизация</a>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>

<div>
    {% block body %}
    {% endblock %}
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

core/templates/developers.html
{% extends 'base.html' %}

{% block body %}

{% load static %}

<div class="card-deck main-background" style="display: flex; justify-content: space-evenly; padding: 50px; margin: 50px;">
  {% for developer in developers %}
  <div class="card" style="width: 300px; margin: 10px">
    <div class="card-header">
      <img style="max-width: 270px;" class="card-img-top" src="{{ developer.image.url }}" alt="Card image cap">
    </div>
    <div class="card-body">
      <h5 class="card-title">{{developer.name}}</h5>
      <p class="card-text">Сайт: <a href="{{developer.site}}">{{developer.site}}</a></p>
      <p class="card-text">Год основания: <b>{{developer.foundation_year}}</b></p>
      <p class="card-text">Номер телефона: <b>{{developer.phone_number}}</b></p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

core/templates/home.html
<!-- templates/home.html -->
<h1>HomePage</h1>

<form action="{% url 'search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
</form>

core/templates/houses.html
{% extends 'base.html' %}

{% block body %}

{% load static %}

    {% for house in houses %}
        <div>
            {{house.name}}<br />
            {{house.year}}<br />
            {{house.number_of_floors}}<br />
            {{house.number_of_apartments}}<br />
            {{house.get_house_class_display}}<br />
            {{house.get_status_display}}<br />
            {{house.get_availability_of_apartments_display}}<br />
            {{house.address}}<br />
            <img src="{{ house.image.url }}">
        </div><br />
    {% endfor %}

{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% block body %}

{% load static %}
<div style="display: flex; justify-content: center;">
    <img style="width: -webkit-fill-available; padding: 50px" src="{% static 'img/house.png' %}">
</div>
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}
{% block body %}

<div class="card-deck" style="display: flex; justify-content: center;">

  <div class="card main-background" style="padding: 50px; margin: 50px; text-align: center;">
    <h2>Авторизация</h2>

    <form method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="form-inline" style="display: flex; align-items: baseline; padding-top: 15px">
        {{ field }}
      </div>
      {% endfor %}
      <div style="padding-top: 30px; display: flex; justify-content: center;">
      <button type="submit" class="btn btn-success">Войти</button>
    </div>
    </form>

    <a href="{% url 'signup' %}" style="padding-top: 30px; display: flex; justify-content: center;">Регистрация</a>
  </div>

</div>

{% endblock %}

core/templates/search.html
{% extends 'base.html' %}

{% block content %}

<form method="GET">
  <div style="display: flex; justify-content: center; flex-wrap: wrap; padding-top: 20px; align-items: flex-end;">
    {% for field in filter.form %}
    {% if field.name == "name" %}
    <div class="form-group row col-md-6" style="display: flex; align-items: baseline; padding-top: 15px; margin-right: 30px">
      <label>{{ field.label }}</label>
      {{ field }}
    </div>
    {% else %}
    <div class="form-group row col-md-2" style="display: flex; align-items: baseline; padding-top: 15px; margin-right: 30px">
      {% if field.name == "developer" %}
      <label>Застройщик</label>
      {% else %}
      <label>{{ field.label }}</label>
      {% endif %}
      {{ field }}
    </div>
    {% endif %}
    {% endfor %}
  </div>
  <div style="padding: 30px; display: flex; justify-content: center;">
    <button type="submit" class="btn btn-success">Поиск</button>
  </div>

</form>

<div class="card-deck main-background" style="display: flex; flex-wrap: wrap; justify-content: space-evenly; padding: 50px; margin-bottom:100px">

  {% if filter.qs %}

  {% for house in filter.qs %}
  <div class="card" style="width: 300px; margin: 20px">
    <div class="card-body" style="display: flex; justify-content: center;">
      <img style="width: 270px" class="card-img-top" src="{{ house.image.url }}" alt="Card image cap">
    </div>
    <div class="card-body">
      <h5 class="card-title" style="margin-bottom: 30px;">{{house.name}}</h5>
      {% if house.get_status_display == "сдан" %}
      <p class="card-text">Статус дома: <span class="badge badge-info">{{house.get_status_display}}</span></p>
      {% else %}
      <p class="card-text">Статус дома: <span class="badge badge-secondary">{{house.get_status_display}}</span></p>
      {% endif %}
      {% if house.get_availability_of_apartments_display == "есть" %}
      <p class="card-text">Наличие квартир: <span class="badge badge-success">{{house.get_availability_of_apartments_display}}</span></p>
      {% else %}
      <p class="card-text">Наличие квартир: <span class="badge badge-danger">{{house.get_availability_of_apartments_display}}</span></p>
      {% endif %}
      <p class="card-text">Адрес: <b>{{house.address}}</b></p>
      <p class="card-text">Класс дома: <b>{{house.get_house_class_display}}</b></p>
      <p class="card-text">Год ввода в эксплуатацию: <b>{{house.year}}</b></p>
      <p class="card-text">Этажность: <b>{{house.number_of_floors}}</b></p>
    </div>
  </div>
  {% endfor %}

  {% else %}
  Не нашлось результатов, удовлетворяющих Вашему запросу
  {% endif %}

</div>

{% endblock %}

core/templates/search_results.html
{% extends 'base.html' %}
{% block body %}

<div class="card-deck main-background" style="display: flex; flex-wrap: wrap; justify-content: space-evenly; padding: 50px; margin:50px">

    {% if not object_list %}
    Не нашлось результатов, удовлетворяющих Вашему запросу
    {% else %}

    {% for object in object_list %}

    {% if object.site %}
    <div class="card" style="width: 300px; margin:10px">
        <div class="card-header">
            <img style="max-width: 270px;" class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
        </div>
        <div class="card-body">
            <h5 class="card-title">{{object.name}}</h5>
            <p class="card-text">Сайт: <a href="{{object.site}}">{{object.site}}</a></p>
            <p class="card-text">Год основания: <b>{{object.foundation_year}}</b></p>
            <p class="card-text">Номер телефона: <b>{{object.phone_number}}</b></p>
        </div>
    </div>
    {% else %}
    <div class="card" style="width: 300px; margin: 10px">
        <div class="card-body" style="display: flex; justify-content: center;">
            <img style="width: 270px" class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
        </div>
        <div class="card-body">
            <h5 class="card-title" style="margin-bottom: 30px;">{{object.name}}</h5>
            {% if object.get_status_display == "сдан" %}
            <p class="card-text">Статус дома: <span class="badge badge-info">{{object.get_status_display}}</span></p>
            {% else %}
            <p class="card-text">Статус дома: <span class="badge badge-secondary">{{object.get_status_display}}</span></p>
            {% endif %}
            {% if object.get_availability_of_apartments_display == "есть" %}
            <p class="card-text">Наличие квартир: <span class="badge badge-success">{{object.get_availability_of_apartments_display}}</span></p>
            {% else %}
            <p class="card-text">Наличие квартир: <span class="badge badge-danger">{{object.get_availability_of_apartments_display}}</span></p>
            {% endif %}
            <p class="card-text">Адрес: <b>{{object.address}}</b></p>
            <p class="card-text">Класс дома: <b>{{object.get_house_class_display}}</b></p>
            <p class="card-text">Год ввода в эксплуатацию: <b>{{object.year}}</b></p>
            <p class="card-text">Этажность: <b>{{object.number_of_floors}}</b></p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
</div>
{% endblock %}

core/templates/signup.html
{% extends 'base.html' %}
{% block body %}

<div class="card-deck" style="display: flex; justify-content: center;">
	<div class="card main-background" style="padding: 50px; margin: 50px;">
		<h2 style="text-align: center;">Регистрация</h2>
		<form method="POST">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group" style="display: flex; align-items: baseline; padding-top: 15px; flex-direction: column;">
				{{ field }}
				<p>
					{% if field.help_text %}
					<small style="color: green">{{ field.help_text }}</small>
					{% endif %}
					{% for error in field.errors %}
					<br /><small style="color: red">{{ error }}</small>
					{% endfor %}
				</p>
			</div>
			{% endfor %}
			<div style="padding-top: 30px; display: flex; justify-content: center;">
				<button type="submit" class="btn btn-success">Зарегистрироваться</button>
			</div>
		</form>
	</div>
</div>

{% endblock %}